### PR TITLE
Add simple setup.py and systemd timer

### PR DESCRIPTION
**Pull request by wesbarnett**

### CODE REVIEW

**Comment by wesbarnett** [comment]
Ah I didn't know that was in the pull request. Doh. Will try to fix.

**Comment by wesbarnett** [comment]
Okay the PKGBUILD is out. That was mainly for me on my system. The intent was to keep it on my own fork and not put it in this pull request. Sorry about that. Should be ready to merge now.

**Comment by boramalper** [comment]
I noticed a problem while trying to set up a timer using systemd on Ubuntu 15.10:

`systemctl --user enable --start himawaripy.timer` commands returns `systemctl: unrecognized option '--start'`. Do you know what might have caused it?

```
$ systemctl --version
systemd 225
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```

**Comment by ghost** [comment]
My setup.py was better in this way :
Mine :
~/pkg/himawaripy-git   master ●  pacman -Ql himawaripy-git 
himawaripy-git /usr/
himawaripy-git /usr/bin/
himawaripy-git /usr/bin/himawaripy

Yours :
~/pkg/himawaripy-git   dev ●  pacman -Ql himawaripy-git 
himawaripy-git /usr/
himawaripy-git /usr/bin/
himawaripy-git /usr/bin/himawaripy
himawaripy-git /usr/bin/himawaripy.py
himawaripy-git /usr/bin/utils.py

My only had one entrypoint into /usr/bin, I dislike this implementation, and I think II'll kept my setup.py in AUR package until this will not be fixed or someone convince me.

**Comment by ghost** [comment]
See https://github.com/boramalper/himawaripy/issues/44 to debate if you want to.

**Pull request merged**
