### PR TITLE
Fixed xfce4 support.

### LINKED ISSUE #4: xfce4 on archlinux
This is the output I get when I run it.  I am on arch, so 'python' is python3 (version included below).
$ python himawaripy.py 
Updating...
Latest version: 2016/02/04/16:20:00 GMT

Downloading tiles: 16/16 completed
Downloaded

Property "/backdrop/screen0/monitor0/image-path" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.
Done!

$ python
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

### PR DESCRIPTION
**Pull request by rbong**
This should fix #4 and possibly #15.  This technically also adds the support for multiple monitors in xfce as well.

### CODE REVIEW

**Comment by boramalper** [comment]
Let's see if this fixes #4 and #15, then I will merge.

Thank you!

**Comment by rbong** [comment]
#4 has been fixed and #15 is not replying.

The newest commit will preserve the previous behaviour. The previous option string used has been placed inside the xfce_displays array, so that this pull request will not break the script for anyone.

**Comment by boramalper** [comment]
Thank you!

I'm merging this now, but maybe we can also parse the output of `xfconf-query --channel xfce4-desktop --list | grep last-image` and automatically set background for every display. Not sure if it's a good idea though, what do you think?

**Comment by rbong** [comment]
I think there's a whole lot of displays in that command. Maybe just adding /backdrop/screen0/monitorHDMI-0/last-image and /backdrop/screen0/monitorLVDS0/last-image (there's no hyphen but this is correct) to that array by default would be enough. If someone is using a second workspace, tty login, or monitor, they'll probably know that they need to configure the script a bit.

In general, I think if there's going to be more multi-monitor support there needs to be a more robust configuration framework.

**Comment by boramalper** [comment]
I'm planing to create a Python library for detecting desktop environment and setting background. It may even evolve by time to include other supposed-to-be-simple OS related functions.

I never imagined that such a trivial task could be that complicated...

**Pull request merged**
