### PR TITLE
Now works correctly on MATE

### PR DESCRIPTION
**Pull request by narhen**
Tried it on MATE and it did not work. Apparently, mate does not use gconftool-2 but gsettings.

### CODE REVIEW

**Comment by boramalper** [comment]
Thanks for the fix! I'm planning to license project under [MIT License](http://choosealicense.com/licenses/mit/), and I need to ask whether it's okay for you, since the project currently has no license.

**Comment by narhen** [comment]
That is okay with me

**Comment by narhen** [comment]
That is okay with me

**Comment by narhen** [comment]
That is okay with me

**Comment by boramalper** [comment]
Thank you!

**Pull request merged**
