### PR TITLE
Add possibility to offset time

### PR DESCRIPTION
**Pull request by dr1s**
I modified the script so someone can add an hourly offset or let python calculate it.
E.g. if someone lives in Europe and doesn't want to see the earth by night when its daytime in Europe.

Sadly you need some more modules to make it work.
- dateutil
- pytz
- tzlocal
- datetime

I'm open for any suggestions to reduce the module dependencies.

### CODE REVIEW

**Comment by wngr** [comment]
That's great, man.

**Comment by dr1s** [comment]
's/local_tz/get_localzone/'

I submitted the pull request to early and forgot to test it, sorry.

**Comment by dr1s** [comment]
Let me send you a clean pull request tomorrow. I close this for now.

**Comment by boramalper** [comment]
Waiting for it! :)

**Pull request closed without merging**
