### PR TITLE
OS X Support

### PR DESCRIPTION
**Pull request by jcmiller11**
Added in support for os x, tested and it works fine on my machine as long as you have python3 and the pillow library installed

### CODE REVIEW

**Comment by jcmiller11** [comment]
Oh, also, depending on how they set up their machine (specifically if they used home-brew to install python3) they may have to change the first line to #!/usr/local/bin/python3

**Comment by boramalper** [comment]
Thanks for adding OS X support, and testing it afterwards. :)

I'm planning to license project under [MIT License](http://choosealicense.com/licenses/mit/), and I need to ask whether it's okay for you, since the project currently has no license. If yes, then I can merge.

@jcmiller11 @cj-zeiger

**Comment by jcmiller11** [comment]
That's cool with me!

**Comment by peteringram0** [comment]
when will this be merged please? Also do you have docs of OSX?

**Comment by boramalper** [comment]
> when will this be merged please? Also do you have docs of OSX?

When @cj-zeiger confirms as well. Also what do you mean by docs?

---

Lastly, I think current async implementation is better than the proposed one, for it shows the progress and it's shorter. Can you please remove that commit (not sure if possible)?

Thanks!

**Comment by jcmiller11** [comment]
Done

**Comment by cj-zeiger** [comment]
@boramalper That's fine by me.

**Comment by jcmiller11** [comment]
> Also what do you mean by docs?

Most OS X users don't have python3 or pillow/PIL installed and must do so and set up the proper path in the context of the cron job.  I'm not very good at writing docs, so maybe some kind soul could add in a little instruction to help Mac users get it up and running.

**Pull request merged**
